### PR TITLE
Updated fort ranks to match 2.51 update

### PR DESCRIPTION
**Pull request by xShteff**

### CODE REVIEW

**Comment by TomRobert** [comment]
Hey xShteff

Can you give me permission to commit to this pull request?

**Comment by xShteff** [comment]
I'd do it if I knew how lel

**Comment by TomRobert** [comment]
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by xShteff** [comment]
Was already checked. https://puu.sh/ufa4v/328b80247e.png

**Comment by TomRobert** [comment]
Okay thanks.
And I don't get it how to commit to your pull request :)
I just made a new pull request with your changes included.

**Pull request merged**
